image: node:alpine

stages:
  - deploy

before_script:
  - apk update
  - apk add git
  - apk add bash
  - "which ssh-agent || ( apk add openssh-client )"
  - eval $(ssh-agent -s)
  - bash -c 'ssh-add <(echo "$SSH_KEY")'
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy:
  stage: deploy
  script:
    - ssh $USER@$HOST "cd /etc/repos/osu-collaboration-bot/; git fetch --all; git reset --hard origin/master; git pull origin master; dotnet publish -c release; supervisorctl restart osu-collaboration-bot"