version: "3.9"
services:
  
  db:
    image: postgres
    restart: unless-stopped
    environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=postgres
    #ports:
      #- 5432:5432  #dangerous if you use default password
    volumes:
      - bot-db:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
  
  bot:
    build: .
    restart: unless-stopped
    environment:
      - App__ConnectionString=Server=db;Port=5432;Database=postgres;User Id=postgres;Password=postgres;
      - App__Token=${App__Token}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - bot-files:/etc/osu_collab_bot/
volumes: 
     bot-db:
     bot-files:
