//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollaborationBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CollaborationBot.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not assign part &apos;{0}&apos; to user &apos;{1}&apos;..
        /// </summary>
        public static string AddAssignmentFail {
            get {
                return ResourceManager.GetString("AddAssignmentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned part &apos;{0}&apos; to user &apos;{1}&apos;..
        /// </summary>
        public static string AddAssignmentSuccess {
            get {
                return ResourceManager.GetString("AddAssignmentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add update notification for project &apos;{0}&apos; to channel {1}..
        /// </summary>
        public static string AddAutoUpdateFail {
            get {
                return ResourceManager.GetString("AddAutoUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added update notification for project &apos;{0}&apos; to channel {1}..
        /// </summary>
        public static string AddAutoUpdateSuccess {
            get {
                return ResourceManager.GetString("AddAutoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add this server..
        /// </summary>
        public static string AddGuildFail {
            get {
                return ResourceManager.GetString("AddGuildFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added this server..
        /// </summary>
        public static string AddGuildSuccess {
            get {
                return ResourceManager.GetString("AddGuildSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not promote {0} to manager of project &apos;{1}&apos;..
        /// </summary>
        public static string AddManagerFailMessage {
            get {
                return ResourceManager.GetString("AddManagerFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoted {0} to manager of project &apos;{1}&apos;..
        /// </summary>
        public static string AddManagerSuccessMessage {
            get {
                return ResourceManager.GetString("AddManagerSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add {0} to project &apos;{1}&apos;..
        /// </summary>
        public static string AddMemberFailMessage {
            get {
                return ResourceManager.GetString("AddMemberFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} to project &apos;{1}&apos;..
        /// </summary>
        public static string AddMemberSuccessMessage {
            get {
                return ResourceManager.GetString("AddMemberSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add part &apos;{0}&apos; to project &apos;{1}&apos;..
        /// </summary>
        public static string AddPartFail {
            get {
                return ResourceManager.GetString("AddPartFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added part &apos;{0}&apos; to project &apos;{1}&apos;..
        /// </summary>
        public static string AddPartSuccess {
            get {
                return ResourceManager.GetString("AddPartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add project with name &apos;{0}&apos;..
        /// </summary>
        public static string AddProjectFail {
            get {
                return ResourceManager.GetString("AddProjectFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added project with name &apos;{0}&apos;..
        /// </summary>
        public static string AddProjectSuccess {
            get {
                return ResourceManager.GetString("AddProjectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases:.
        /// </summary>
        public static string Aliases {
            get {
                return ResourceManager.GetString("Aliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All member tags: ```{0}``` .
        /// </summary>
        public static string AllMemberTags {
            get {
                return ResourceManager.GetString("AllMemberTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already a member of this project..
        /// </summary>
        public static string AlreadyJoinedMessage {
            get {
                return ResourceManager.GetString("AlreadyJoinedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not finish part &apos;{1}&apos; of project &apos;{2}&apos; before the deadline. The part is now available for claiming again..
        /// </summary>
        public static string AssignmentDeadlinePassed {
            get {
                return ResourceManager.GetString("AssignmentDeadlinePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are all the assignments of the project:.
        /// </summary>
        public static string AssignmentListMessage {
            get {
                return ResourceManager.GetString("AssignmentListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This assignment does not exist..
        /// </summary>
        public static string AssignmentNotExists {
            get {
                return ResourceManager.GetString("AssignmentNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attached file is invalid..
        /// </summary>
        public static string AttachedFileInvalid {
            get {
                return ResourceManager.GetString("AttachedFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change `auto cleanup` of project &apos;{0}&apos; to {1}..
        /// </summary>
        public static string AutoCleanupChangeFail {
            get {
                return ResourceManager.GetString("AutoCleanupChangeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed `auto cleanup` of project &apos;{0}&apos; to {1}..
        /// </summary>
        public static string AutoCleanupChangeSuccess {
            get {
                return ResourceManager.GetString("AutoCleanupChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change cooldown for update notification..
        /// </summary>
        public static string AutoUpdateCooldownFail {
            get {
                return ResourceManager.GetString("AutoUpdateCooldownFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed cooldown for update notification for project &apos;{0}&apos; to {1}..
        /// </summary>
        public static string AutoUpdateCooldownSuccess {
            get {
                return ResourceManager.GetString("AutoUpdateCooldownSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change mention configuration for update notification..
        /// </summary>
        public static string AutoUpdateDoPingFail {
            get {
                return ResourceManager.GetString("AutoUpdateDoPingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed mention configuration for update notification to {0}..
        /// </summary>
        public static string AutoUpdateDoPingSuccess {
            get {
                return ResourceManager.GetString("AutoUpdateDoPingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s the latest .osu beatmap version of project &apos;{0}&apos;..
        /// </summary>
        public static string AutoUpdateLatest {
            get {
                return ResourceManager.GetString("AutoUpdateLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Here&apos;s the latest .osu beatmap version of project &apos;{1}&apos;..
        /// </summary>
        public static string AutoUpdateLatestMention {
            get {
                return ResourceManager.GetString("AutoUpdateLatestMention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no update notification for project &apos;{0}&apos; and channel {1}..
        /// </summary>
        public static string AutoUpdateNotExists {
            get {
                return ResourceManager.GetString("AutoUpdateNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not trigger update notification for project &apos;{0}&apos;..
        /// </summary>
        public static string AutoUpdateTriggerFail {
            get {
                return ResourceManager.GetString("AutoUpdateTriggerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggered update notification for project &apos;{0}&apos;..
        /// </summary>
        public static string AutoUpdateTriggerSuccess {
            get {
                return ResourceManager.GetString("AutoUpdateTriggerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while processing the request on our backend..
        /// </summary>
        public static string BackendErrorMessage {
            get {
                return ResourceManager.GetString("BackendErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base file of the project is missing..
        /// </summary>
        public static string BaseFileNotExists {
            get {
                return ResourceManager.GetString("BaseFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse osu! beatmap: ```{0}```.
        /// </summary>
        public static string BeatmapParseFail {
            get {
                return ResourceManager.GetString("BeatmapParseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change alias..
        /// </summary>
        public static string ChangeAliasFail {
            get {
                return ResourceManager.GetString("ChangeAliasFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed alias of {0} to &apos;{1}&apos;..
        /// </summary>
        public static string ChangeAliasSuccess {
            get {
                return ResourceManager.GetString("ChangeAliasSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change manager role for project &apos;{0}&apos;..
        /// </summary>
        public static string ChangeManagerRoleFail {
            get {
                return ResourceManager.GetString("ChangeManagerRoleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed manager role for project &apos;{0}&apos; to `{1}`..
        /// </summary>
        public static string ChangeManagerRoleSuccess {
            get {
                return ResourceManager.GetString("ChangeManagerRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change role for project &apos;{0}&apos;..
        /// </summary>
        public static string ChangeProjectRoleFail {
            get {
                return ResourceManager.GetString("ChangeProjectRoleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed role for project &apos;{0}&apos; to `{1}`..
        /// </summary>
        public static string ChangeProjectRoleSuccess {
            get {
                return ResourceManager.GetString("ChangeProjectRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change color of roles of project &apos;{0}&apos; to {1}..
        /// </summary>
        public static string ChangeRoleColorFail {
            get {
                return ResourceManager.GetString("ChangeRoleColorFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed color of roles of project &apos;{0}&apos; to {1}..
        /// </summary>
        public static string ChangeRoleColorSuccess {
            get {
                return ResourceManager.GetString("ChangeRoleColorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change tags..
        /// </summary>
        public static string ChangeTagsFail {
            get {
                return ResourceManager.GetString("ChangeTagsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed tags of {0} to `{1}`..
        /// </summary>
        public static string ChangeTagsSuccess {
            get {
                return ResourceManager.GetString("ChangeTagsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command `{0}` could not be found..
        /// </summary>
        public static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you are not authorized to use this command..
        /// </summary>
        public static string CommandUnauthorized {
            get {
                return ResourceManager.GetString("CommandUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the CSV file with the part information. Make sure it uses the correct format..
        /// </summary>
        public static string CouldNotReadPartCSV {
            get {
                return ResourceManager.GetString("CouldNotReadPartCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you have 48 hours left to complete part &apos;{1}&apos; for project &apos;{2}&apos;..
        /// </summary>
        public static string DeadlineReminder {
            get {
                return ResourceManager.GetString("DeadlineReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted channel.
        /// </summary>
        public static string DeletedChannel {
            get {
                return ResourceManager.GetString("DeletedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not edit part..
        /// </summary>
        public static string EditPartFail {
            get {
                return ResourceManager.GetString("EditPartFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully edited part..
        /// </summary>
        public static string EditPartSuccess {
            get {
                return ResourceManager.GetString("EditPartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not mark part as finished..
        /// </summary>
        public static string FinishPartFail {
            get {
                return ResourceManager.GetString("FinishPartFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part &apos;{0}&apos; is now finished..
        /// </summary>
        public static string FinishPartSuccess {
            get {
                return ResourceManager.GetString("FinishPartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not generate priorities for members of project &apos;{0}&apos;..
        /// </summary>
        public static string GeneratePrioritiesFail {
            get {
                return ResourceManager.GetString("GeneratePrioritiesFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated priorities for member of project &apos;{0}&apos;..
        /// </summary>
        public static string GeneratePrioritiesSuccess {
            get {
                return ResourceManager.GetString("GeneratePrioritiesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change collab category to `{0}`..
        /// </summary>
        public static string GuildCollabCategoryFail {
            get {
                return ResourceManager.GetString("GuildCollabCategoryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed collab category to `{0}`..
        /// </summary>
        public static string GuildCollabCategorySuccess {
            get {
                return ResourceManager.GetString("GuildCollabCategorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is already registered..
        /// </summary>
        public static string GuildExistsMessage {
            get {
                return ResourceManager.GetString("GuildExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change max collab count per person to {0}..
        /// </summary>
        public static string GuildMaxCollabsFail {
            get {
                return ResourceManager.GetString("GuildMaxCollabsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed max collab count per person to {0}..
        /// </summary>
        public static string GuildMaxCollabsSuccess {
            get {
                return ResourceManager.GetString("GuildMaxCollabsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your server is not registered! You can add it via command &apos;!!guild init&apos;..
        /// </summary>
        public static string GuildNotExistsMessage {
            get {
                return ResourceManager.GetString("GuildNotExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not a valid filename..
        /// </summary>
        public static string IllegalFilename {
            get {
                return ResourceManager.GetString("IllegalFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not a valid input..
        /// </summary>
        public static string IllegalInput {
            get {
                return ResourceManager.GetString("IllegalInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not a valid project name..
        /// </summary>
        public static string IllegalProjectName {
            get {
                return ResourceManager.GetString("IllegalProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s a list of commands and their description:.
        /// </summary>
        public static string ListCommandsMessage {
            get {
                return ResourceManager.GetString("ListCommandsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are only allowed to have {0} active assignments..
        /// </summary>
        public static string MaxAssignmentsReached {
            get {
                return ResourceManager.GetString("MaxAssignmentsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already reached the maximum number of collabs ({0})..
        /// </summary>
        public static string MaxCollabCountReached {
            get {
                return ResourceManager.GetString("MaxCollabCountReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is already a member of the project..
        /// </summary>
        public static string MemberExistsMessage {
            get {
                return ResourceManager.GetString("MemberExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are all members of the project:.
        /// </summary>
        public static string MemberListMessage {
            get {
                return ResourceManager.GetString("MemberListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not a member of the project..
        /// </summary>
        public static string MemberNotExistsMessage {
            get {
                return ResourceManager.GetString("MemberNotExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not move deadline to {0}..
        /// </summary>
        public static string MoveDeadlineFail {
            get {
                return ResourceManager.GetString("MoveDeadlineFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved deadline to {0}..
        /// </summary>
        public static string MoveDeadlineSuccess {
            get {
                return ResourceManager.GetString("MoveDeadlineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove parts from project &apos;{0}&apos;..
        /// </summary>
        public static string MultiRemovePartFail {
            get {
                return ResourceManager.GetString("MultiRemovePartFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0} parts from project &apos;{1}&apos;..
        /// </summary>
        public static string MultiRemovePartSuccess {
            get {
                return ResourceManager.GetString("MultiRemovePartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no assignments in this project..
        /// </summary>
        public static string NoAssignments {
            get {
                return ResourceManager.GetString("NoAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an attached file..
        /// </summary>
        public static string NoAttachedFile {
            get {
                return ResourceManager.GetString("NoAttachedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description available..
        /// </summary>
        public static string NoDescription {
            get {
                return ResourceManager.GetString("NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no members of this project..
        /// </summary>
        public static string NoMembers {
            get {
                return ResourceManager.GetString("NoMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no parts in this project..
        /// </summary>
        public static string NoParts {
            get {
                return ResourceManager.GetString("NoParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any assigned parts to submit to..
        /// </summary>
        public static string NoPartsToSubmit {
            get {
                return ResourceManager.GetString("NoPartsToSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no projects in this server..
        /// </summary>
        public static string NoProjects {
            get {
                return ResourceManager.GetString("NoProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not assigned to this part..
        /// </summary>
        public static string NotAssigned {
            get {
                return ResourceManager.GetString("NotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not a member of this project..
        /// </summary>
        public static string NotJoinedMessage {
            get {
                return ResourceManager.GetString("NotJoinedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project is currently not looking for members..
        /// </summary>
        public static string NotLookingForMembers {
            get {
                return ResourceManager.GetString("NotLookingForMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}guild help
        ///{0}part help
        ///{0}asn help
        ///{0}au help.
        /// </summary>
        public static string OtherModuleHelpGuide {
            get {
                return ResourceManager.GetString("OtherModuleHelpGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the help command on other modules for more information:.
        /// </summary>
        public static string OtherModuleHelpReference {
            get {
                return ResourceManager.GetString("OtherModuleHelpReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is owner of project &apos;{0}&apos; and can&apos;t be demoted. Transfer ownership with `set-owner` first..
        /// </summary>
        public static string OwnerCannotBeDemotedMessage {
            get {
                return ResourceManager.GetString("OwnerCannotBeDemotedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project owner can&apos;t leave their own project. Transfer ownership with `set-owner` first..
        /// </summary>
        public static string OwnerCannotLeaveMessage {
            get {
                return ResourceManager.GetString("OwnerCannotLeaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This part has been claimed already..
        /// </summary>
        public static string PartClaimedAlready {
            get {
                return ResourceManager.GetString("PartClaimedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import parts from the CSV file into project &apos;{0}&apos;..
        /// </summary>
        public static string PartFromCSVFail {
            get {
                return ResourceManager.GetString("PartFromCSVFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported parts from the CSV file into project &apos;{0}&apos;..
        /// </summary>
        public static string PartFromCSVSuccess {
            get {
                return ResourceManager.GetString("PartFromCSVSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are all the parts of the project:.
        /// </summary>
        public static string PartListMessage {
            get {
                return ResourceManager.GetString("PartListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A part named &apos;{0}&apos; does not exist in project &apos;{1}&apos;..
        /// </summary>
        public static string PartNotExists {
            get {
                return ResourceManager.GetString("PartNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not export all parts of project &apos;{0}&apos; to CSV..
        /// </summary>
        public static string PartToCSVFail {
            get {
                return ResourceManager.GetString("PartToCSVFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported all parts of project &apos;{0}&apos; to CSV:.
        /// </summary>
        public static string PartToCSVSuccess {
            get {
                return ResourceManager.GetString("PartToCSVSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change priority of member {0} to {1}..
        /// </summary>
        public static string PriorityChangeFail {
            get {
                return ResourceManager.GetString("PriorityChangeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed priority of member {0} to {1}..
        /// </summary>
        public static string PriorityChangeSuccess {
            get {
                return ResourceManager.GetString("PriorityChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) stole part {2} from {3} ({4}), oh the humanity!.
        /// </summary>
        public static string PriorityPartSteal {
            get {
                return ResourceManager.GetString("PriorityPartSteal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project has already been set-up..
        /// </summary>
        public static string ProjectAlreadySetup {
            get {
                return ResourceManager.GetString("ProjectAlreadySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change default lifetime of assignments in project &apos;{0}&apos;..
        /// </summary>
        public static string ProjectAssignmentLifetimeFail {
            get {
                return ResourceManager.GetString("ProjectAssignmentLifetimeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed default lifetime of assignments in project &apos;{0}&apos; to {1}..
        /// </summary>
        public static string ProjectAssignmentLifetimeSuccess {
            get {
                return ResourceManager.GetString("ProjectAssignmentLifetimeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change description for project &apos;{0}&apos;..
        /// </summary>
        public static string ProjectDescriptionFail {
            get {
                return ResourceManager.GetString("ProjectDescriptionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed description for project &apos;{0}&apos;..
        /// </summary>
        public static string ProjectDescriptionSuccess {
            get {
                return ResourceManager.GetString("ProjectDescriptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project already exists..
        /// </summary>
        public static string ProjectExistsMessage {
            get {
                return ResourceManager.GetString("ProjectExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change project info channel to {0}..
        /// </summary>
        public static string ProjectInfoChannelFail {
            get {
                return ResourceManager.GetString("ProjectInfoChannelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed project info channel to {0}..
        /// </summary>
        public static string ProjectInfoChannelSuccess {
            get {
                return ResourceManager.GetString("ProjectInfoChannelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are all the projects in the server:.
        /// </summary>
        public static string ProjectListMessage {
            get {
                return ResourceManager.GetString("ProjectListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change project main channel to {0}..
        /// </summary>
        public static string ProjectMainChannelFail {
            get {
                return ResourceManager.GetString("ProjectMainChannelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed project main channel to {0}..
        /// </summary>
        public static string ProjectMainChannelSuccess {
            get {
                return ResourceManager.GetString("ProjectMainChannelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change max assignment count of project &apos;{0}&apos;..
        /// </summary>
        public static string ProjectMaxAssignmentsFail {
            get {
                return ResourceManager.GetString("ProjectMaxAssignmentsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed max assignment count of project &apos;{0}&apos; to {1}..
        /// </summary>
        public static string ProjectMaxAssignmentsSuccess {
            get {
                return ResourceManager.GetString("ProjectMaxAssignmentsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project does not exist..
        /// </summary>
        public static string ProjectNotExistMessage {
            get {
                return ResourceManager.GetString("ProjectNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change options of project &apos;{0}&apos;..
        /// </summary>
        public static string ProjectOptionsFail {
            get {
                return ResourceManager.GetString("ProjectOptionsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed {0} options of project &apos;{1}&apos;..
        /// </summary>
        public static string ProjectOptionsSuccess {
            get {
                return ResourceManager.GetString("ProjectOptionsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not rename project &apos;{0}&apos; to project &apos;{1}&apos;..
        /// </summary>
        public static string ProjectRenameFail {
            get {
                return ResourceManager.GetString("ProjectRenameFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed project &apos;{0}&apos; to project &apos;{1}&apos;..
        /// </summary>
        public static string ProjectRenameSuccess {
            get {
                return ResourceManager.GetString("ProjectRenameSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change status of project &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        public static string ProjectStatusFail {
            get {
                return ResourceManager.GetString("ProjectStatusFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed status of project &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        public static string ProjectStatusSuccess {
            get {
                return ResourceManager.GetString("ProjectStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove assignment from user &apos;{0}&apos;..
        /// </summary>
        public static string RemoveAssignmentFail {
            get {
                return ResourceManager.GetString("RemoveAssignmentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed assignment from user &apos;{0}&apos;..
        /// </summary>
        public static string RemoveAssignmentSuccess {
            get {
                return ResourceManager.GetString("RemoveAssignmentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove update notification for project &apos;{0}&apos; from channel {1}..
        /// </summary>
        public static string RemoveAutoUpdateFail {
            get {
                return ResourceManager.GetString("RemoveAutoUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed update notification for project &apos;{0}&apos; from channel {1}..
        /// </summary>
        public static string RemoveAutoUpdateSuccess {
            get {
                return ResourceManager.GetString("RemoveAutoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed deadline for user &apos;{0}&apos;..
        /// </summary>
        public static string RemoveDeadlineSuccess {
            get {
                return ResourceManager.GetString("RemoveDeadlineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not demote {0} to a regular member of &apos;{1}&apos;..
        /// </summary>
        public static string RemoveManagerFailMessage {
            get {
                return ResourceManager.GetString("RemoveManagerFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demoted {0} to a regular member of &apos;{1}&apos;..
        /// </summary>
        public static string RemoveManagerSuccessMessage {
            get {
                return ResourceManager.GetString("RemoveManagerSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove {0} from project &apos;{1}&apos;..
        /// </summary>
        public static string RemoveMemberFailMessage {
            get {
                return ResourceManager.GetString("RemoveMemberFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0} from project &apos;{1}&apos;..
        /// </summary>
        public static string RemoveMemberSuccessMessage {
            get {
                return ResourceManager.GetString("RemoveMemberSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove part &apos;{0}&apos; from project &apos;{1}&apos;..
        /// </summary>
        public static string RemovePartFail {
            get {
                return ResourceManager.GetString("RemovePartFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed part &apos;{0}&apos; from project &apos;{1}&apos;..
        /// </summary>
        public static string RemovePartSuccess {
            get {
                return ResourceManager.GetString("RemovePartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove project &apos;{0}&apos;..
        /// </summary>
        public static string RemoveProjectFail {
            get {
                return ResourceManager.GetString("RemoveProjectFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed project &apos;{0}&apos;..
        /// </summary>
        public static string RemoveProjectSuccess {
            get {
                return ResourceManager.GetString("RemoveProjectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-assignment is not allowed at the moment..
        /// </summary>
        public static string SelfAssignmentNotAllowed {
            get {
                return ResourceManager.GetString("SelfAssignmentNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not transfer ownership of project &apos;{0}&apos; to {1}..
        /// </summary>
        public static string SetOwnerFailMessage {
            get {
                return ResourceManager.GetString("SetOwnerFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfered ownership of project &apos;{0}&apos; to {1}..
        /// </summary>
        public static string SetOwnerSuccessMessage {
            get {
                return ResourceManager.GetString("SetOwnerSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set-up project &apos;{0}&apos;..
        /// </summary>
        public static string SetupFail {
            get {
                return ResourceManager.GetString("SetupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully set-up project &apos;{0}&apos;..
        /// </summary>
        public static string SetupSuccess {
            get {
                return ResourceManager.GetString("SetupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiled .osu file of project &apos;{0}&apos;:.
        /// </summary>
        public static string ShowBaseFile {
            get {
                return ResourceManager.GetString("ShowBaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted file has no hit objects or you have no open assignments for the submitted parts..
        /// </summary>
        public static string SubmitNoHitObjects {
            get {
                return ResourceManager.GetString("SubmitNoHitObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong when submitting part for project &apos;{0}&apos;..
        /// </summary>
        public static string SubmitPartFailMessage {
            get {
                return ResourceManager.GetString("SubmitPartFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully submitted {0} hit objects to project &apos;{1}&apos;..
        /// </summary>
        public static string SubmitPartSuccessMessage {
            get {
                return ResourceManager.GetString("SubmitPartSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a test string! The quick brown fox jumped over the lazy dog..
        /// </summary>
        public static string TestString {
            get {
                return ResourceManager.GetString("TestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This text channel does not exist..
        /// </summary>
        public static string TextChannelNotExist {
            get {
                return ResourceManager.GetString("TextChannelNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while trying to upload the base file..
        /// </summary>
        public static string UploadBaseFileFail {
            get {
                return ResourceManager.GetString("UploadBaseFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully uploaded `{0}` as base file for project &apos;{1}&apos;..
        /// </summary>
        public static string UploadBaseFileSuccess {
            get {
                return ResourceManager.GetString("UploadBaseFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is already a manager of project &apos;{0}&apos;..
        /// </summary>
        public static string UserAlreadyManagerMessage {
            get {
                return ResourceManager.GetString("UserAlreadyManagerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is already owner of project &apos;{0}&apos;..
        /// </summary>
        public static string UserAlreadyOwnerMessage {
            get {
                return ResourceManager.GetString("UserAlreadyOwnerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not a manager of project &apos;{0}&apos;..
        /// </summary>
        public static string UserNotManagerMessage {
            get {
                return ResourceManager.GetString("UserNotManagerMessage", resourceCulture);
            }
        }
    }
}
